import { Poppins, Inter } from "next/font/google";
import "./globals.css";

import NavbarPage from "@/component/Navbar";
import Footer from "@/component/Footer";
import { Toaster } from "react-hot-toast";
import NextThemeProvider from "@/providers/NextThemeProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "IdeaVault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${poppins.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NextThemeProvider>
          <NavbarPage />

          {children}

          <Toaster position="top-center" />

          <Footer />
        </NextThemeProvider>
      </body>
    </html>
  );
}